### ISSUE TITLE
Error: port bind failed due to address not available

### ISSUE THREAD

**Issue by bhaskarvgurram** [mkhahani/mediasoup-sample-app#1]
This is the error I am getting when I click publish

`(node:31538) UnhandledPromiseRejectionWarning: Error: port bind failed due to address not available [udp:192.168.1.100, attempt:1]
    at Channel._processMessage (/Users/bhaskargurram/RA/mediasoup-sample-app/node_modules/mediasoup/lib/Channel.js:284:19)
    at Socket.Channel._socket.on (/Users/bhaskargurram/RA/mediasoup-sample-app/node_modules/mediasoup/lib/Channel.js:101:13)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
(node:31538) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)`

**Comment by mkhahani** [comment]
You need to edit the `config.js` file and set your server IP:
https://github.com/mkhahani/mediasoup-sample-app/blob/6eb2a7f4db000b12ae198360de5ea9a7ad391f0c/config.example.js#L50

**Comment by bhaskarvgurram** [comment]
> This is the error I am getting when I click publish
> 
> `(node:31538) UnhandledPromiseRejectionWarning: Error: port bind failed due to address not available [udp:192.168.1.100, attempt:1] at Channel._processMessage (/Users/bhaskargurram/RA/mediasoup-sample-app/node_modules/mediasoup/lib/Channel.js:284:19) at Socket.Channel._socket.on (/Users/bhaskargurram/RA/mediasoup-sample-app/node_modules/mediasoup/lib/Channel.js:101:13) at Socket.emit (events.js:189:13) at addChunk (_stream_readable.js:284:12) at readableAddChunk (_stream_readable.js:265:11) at Socket.Readable.push (_stream_readable.js:220:10) at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) (node:31538) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)`

Changed WebRtcTransport listenIps in config.js and it is working
