### ISSUE TITLE
Do not use latest as versions for mediasoup and mediasoup-client in package.json

### ISSUE THREAD

**Issue by applegrew** [mkhahani/mediasoup-sample-app#10]
As of today this what we see on https://www.npmjs.com/package/mediasoup-client for mediasoup-client module.

<img width="1504" alt="Screenshot 2020-01-20 at 12 22 38 AM" src="https://user-images.githubusercontent.com/434574/72686590-5f2b0780-3b1c-11ea-8332-4f7238be4593.png">

mediasoup still maintains both version 2 & 3, and in this case 2 days ago they made an update to version 2 of mediasoup-client, causing it to become the `latest`. Because of that in my local I got error on the browser saying that `mediasoup.Device` is not constructor as that is undefined.

The fix is, change package.json from

    "mediasoup": "latest",
    "mediasoup-client": "latest",

to

    "mediasoup": "3.4.8",
    "mediasoup-client": "3.3.12",

**Comment by mkhahani** [comment]
Ah! you're right. According to the [documentation](https://docs.npmjs.com/misc/semver#x-ranges-12x-1x-12-) it would be better to use the following syntax so it always uses the latest v3:
```
"mediasoup": "3",
"mediasoup-client": "3",
```

**Comment by mkhahani** [comment]
Fixed. Thank you.
