### ISSUE TITLE
Question about sample

### ISSUE THREAD

**Issue by h5aaimtron** [mkhahani/mediasoup-sample-app#13]
Hi,

I had a quick question, confirmation really. This sample assumes all clients that connect would be grouped together yes? So I could use this sample as the basis for a multi group voice where each group has their own voice chat correct? Based on the code I'm assuming this is what it does. Any answer is appreciated.

Thanks Again!

**Comment by mkhahani** [comment]
Hi,

Correct. As the project name implies this is just a sample and you need to do a lot more for a real business application.
