### ISSUE TITLE
 Audio transmission problems

### ISSUE THREAD

**Issue by thoopring** [mkhahani/mediasoup-sample-app#14]
Hi, Developer.
Your collarhub is very helpful. I am inquiring about the issue during the test. I want to play screen and computer sound.

I have modified the getUserMedia function, but I still have no sound.

//============================================
async function getUserMedia(transport, isWebcam) {
if (!device.canProduce('video')) {
console.error('cannot produce video');
return;
}

let stream;
try {
stream = isWebcam ?
Await Navigator.mediaDevices.getUserMedia({ "audio": true, "video": true }) :
await Navigator.mediaDevices.getDisplayMedia({ "audio": true, "video": true });
} catch (err) {
console.error('getUserMedia() filed:', err.message);
through err;
}
return stream;
}

//============================================

**Comment by mkhahani** [comment]
The app is not designed for sending/receiving multiple tracks so you need to customize both the server and the client code for that.

**Comment by yarekc** [comment]
Hi,
Could not make it run: it connects correctly, I can start Webcam (my webcam switches on), but nothing happens on the screen 

#localVideo is black.

Here  is the screenshot

http://prntscr.com/rtjcns
