### ISSUE TITLE
how can I use H264?

### ISSUE THREAD

**Issue by huyu1** [mkhahani/mediasoup-sample-app#16]
my config:
router: {
      mediaCodecs:
        [
          {
            kind: 'audio',
            mimeType: 'audio/opus',
            clockRate: 48000,
            channels: 2
          },
          {
            kind: 'video',
            mimeType: 'video/VP8',
            clockRate: 90000,
            parameters:
            {
              'x-google-start-bitrate': 1000
            }
          },
          {
            kind: 'video',
            mimeType: 'video/VP9',
            clockRate: 90000,
            parameters:
            {
              'profile-id': 2,
              'x-google-start-bitrate': 1000
            }
          },
          {
            kind       : 'video',
            mimeType   : 'video/h264',
            clockRate  : 90000,
            parameters :
            {
              'packetization-mode'      : 1,
              'profile-level-id'        : '4d0032',
              'level-asymmetry-allowed' : 1,
              'x-google-start-bitrate'  : 4096
            }
          },
          {
            kind       : 'video',
            mimeType   : 'video/h264',
            clockRate  : 90000,
            parameters :
            {
              'packetization-mode'      : 1,
              'profile-level-id'        : '42e01f',
              'level-asymmetry-allowed' : 1,
              'x-google-start-bitrate'  : 4096
            }
          }

////////////////////////////////////////////////////////////////////////////////
//my  serve code:

let videoTransport = await this.mediasoupRouter.createPlainTransport(this.config.mediasoup.plainRtpTransport);

        // Read the transport local RTP port.
        const videoRtpPort = videoTransport.tuple.localPort;
        console.log(videoRtpPort);
        // => 3501

        // Read the transport local RTCP port.
        const videoRtcpPort = videoTransport.rtcpTuple.localPort;
        console.log(videoRtcpPort);
        // => 2989

        let videoProducer = await videoTransport.produce(
            {
                kind: 'video',
                rtpParameters:
                {
                    codecs:
                        [
                            {
                                mimeType     : 'video/h264',
                                clockRate    : 90000,
                                payloadType  : 102,
                                parameters :
                                {
                                    'packetization-mode'      : 1,
                                    'profile-level-id'        : '4d0032',
                                    'level-asymmetry-allowed' : 1,
                                    'x-google-start-bitrate'  : 4096
                                }
                            }
                        ],
                    encodings: [{ ssrc: 22222222 }]
                }
            });
            await videoProducer.enableTraceEvent([ "rtp", "pli" ]);

            videoProducer.on("trace", (trace) =>
            {
              console.log(trace)
            });

///////////////////////////////////////////////////
my ffmpeg:
 ffmpeg -i "rtsp://admin:admin123@192.168.1.82:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif" -an -c copy -ssrc 22222222 -payload_type 102 -f rtp "rtp://192.168.125.128:10098?rtcpport=10096"

//////////////////////////////////////////////////

I can play this h264 in chrome, but, this is very  stuck, VP8 is ok,how can I do?
  
.....

**Comment by huyu1** [comment]
@mkhahani   how can I do?

**Comment by mkhahani** [comment]
Sorry for the late answer. Please ask in the mediasoup forum.
