### ISSUE TITLE
ICE failed, add a STUN server and see about:webrtc for more details

### ISSUE THREAD

**Issue by TheDanielMoli** [mkhahani/mediasoup-sample-app#17]
Hello everyone!

I can't get this demo to work, it seems that I should add the required ICE servers. Am I right? Where should I add them?

Thank you in advance!

**Comment by mkhahani** [comment]
Hi

No, you don't need to use ICE servers except your server does not have public IP. Make sure you've set the right IP in the configuration file.

**Comment by TheDanielMoli** [comment]
Thank you, it works! I was using 127.0.0.1 instead of the machine IP.
