### ISSUE TITLE
Firefox: ICE failed, add a STUN server and see about:webrtc for more details

### ISSUE THREAD

**Issue by doublex** [mkhahani/mediasoup-sample-app#18]
Chrome works.

````
mediasoup-client:Transport consume() | Consumer for RTP probation created +585ms app-bundle.js:6219:10
mediasoup-client:Transport connection state changed to connecting +131ms app-bundle.js:6219:10
WebRTC: ICE failed, add a STUN server and see about:webrtc for more details
mediasoup-client:Transport connection state changed to failed +5s app-bundle.js:6219:10
mediasoup-client:Transport close() +6ms app-bundle.js:6219:10
mediasoup-client:Firefox60 close() +5s app-bundle.js:6219:10
mediasoup-client:Consumer transportClosed() +5s app-bundle.js:6219:10
````

**Comment by mkhahani** [comment]
No idea honestly! Setting your public IP in the [configuration](https://github.com/mkhahani/mediasoup-sample-app/blob/4c26c1e998d5e3c33dee6e5f4137377463e5ed0b/config.example.js#L51) and opening the [port range](https://github.com/mkhahani/mediasoup-sample-app/blob/4c26c1e998d5e3c33dee6e5f4137377463e5ed0b/config.example.js#L9-L10) in your firewall should be enough except something (e.g. an add-on) is blocking the connection.

**Comment by doublex** [comment]
You are right!
Thanks a lot for this great demo.

**Comment by azhar1038** [comment]
@doublex  how did you solve this?
