### ISSUE TITLE
Deploying on Heroku

### ISSUE THREAD

**Issue by TheLonelyAstronaut** [mkhahani/mediasoup-sample-app#19]
Hi!

Is it possible to deploy this project on Heroku? After deployment and setting server address in the client I have this state in my chrome debug console (no errors on the heroku console):
![image](https://user-images.githubusercontent.com/50376577/84931890-1e8be600-b0dc-11ea-9472-da9d85d98b13.png)

I've got only 'connecting' and 'disconneted' (after 15 seconds) statements, without 'connected statement'

How can I solve this issue?

**Comment by mkhahani** [comment]
No idea honestly, zero experience with Heroku. Make sure you've set the right IP address in the configuration and have opened the port range in your firewall.

**Comment by mdazharuddin1011999** [comment]
@TheLonelyAstronaut were you able to solve the problem?
