### ISSUE TITLE
a question about the code not a issue.

### ISSUE THREAD

**Issue by seamory** [mkhahani/mediasoup-sample-app#20]
i had read the code of the project. but i don't understand why socket client could send the promise resolve to the socket server. is the socket server will return the resolved data to the sender or return the resolved data to all socket client? could you tell me the theory of that? and why not use the socket.emit to return the data to the sender.
thank you very much.

**Comment by mkhahani** [comment]
It's the feature of socket.io that accepts callback when emiting a message:
https://github.com/mkhahani/mediasoup-sample-app/blob/4c26c1e998d5e3c33dee6e5f4137377463e5ed0b/lib/socket.io-promise.js#L5

**Comment by seamory** [comment]
thanks, i know that feature, but i don't understand why the callback function is resolve in promise. it's unimaginable the server could return the resolve of client promise.

**Comment by mkhahani** [comment]
The 'resolve' here is just a function. The server does nothing with the Promise.

**Comment by seamory** [comment]
i guess i'm clear. thanks very much!
