### ISSUE TITLE
Neither sending nor receiving video

### ISSUE THREAD

**Issue by azhar1038** [mkhahani/mediasoup-sample-app#23]
I am using Docker on Windows to run the app. After pressing **Start Webcam** only webcam starts but noting happens. Same for **Subscribe**.
![Screenshot (84)](https://user-images.githubusercontent.com/42082172/98444953-dd53ab80-213a-11eb-8fb3-9b7439ccb75d.png)
![Screenshot (87)](https://user-images.githubusercontent.com/42082172/98444958-e8a6d700-213a-11eb-8b6c-ea64593950cd.png)

Nothing is printed to server console.  
  
Chrome console says "mediasoup-client: Transport connection state changed to disconnected"  
  
Help please :)

**Comment by azhar1038** [comment]
Also I was able to run the [mediasoup-demo](https://github.com/versatica/mediasoup-demo) without problem. But this one is not working and this is my config.js file:  
```js
module.exports = {
  listenIp: '0.0.0.0',
  listenPort: 3000,
  sslCrt: '/service/certs/fullchain.pem',
  sslKey: '/service/certs/privkey.pem',
  mediasoup: {
    // Worker settings
    worker: {
      rtcMinPort: 10000,
      rtcMaxPort: 10100,
      logLevel: 'warn',
      logTags: [
        'info',
        'ice',
        'dtls',
        'rtp',
        'srtp',
        'rtcp',
        // 'rtx',
        // 'bwe',
        // 'score',
        // 'simulcast',
        // 'svc'
      ],
    },
    // Router settings
    router: {
      mediaCodecs:
        [
          {
            kind: 'audio',
            mimeType: 'audio/opus',
            clockRate: 48000,
            channels: 2
          },
          {
            kind: 'video',
            mimeType: 'video/VP8',
            clockRate: 90000,
            parameters:
              {
                'x-google-start-bitrate': 1000
              }
          },
        ]
    },
    // WebRtcTransport settings
    webRtcTransport: {
      listenIps: [
        {
          ip: '127.0.0.1',
          announcedIp: '192.168.43.225',
        }
      ],
      maxIncomingBitrate: 1500000,
      initialAvailableOutgoingBitrate: 1000000,
    }
  }
};
```

**Comment by mkhahani** [comment]
Except the server is behind NAT or proxy you don't need to set the `announcedIp` and setting the `ip` with the server IP would be enough.

**Comment by azhar1038** [comment]
I changed the config.js with this:
```js
     listenIps: [
        {
          ip: '192.168.43.225',
          announcedIp: null,
        }
      ],
```  
`192.168.43.225` is my local IP and definitely it is not behind a NAT or proxy but now I am getting this error in server console:
```
Error: port bind failed due to address not available [transport:udp, ip:'192.168.43.225', port:10001, attempt:1/101]
    at Channel._processMessage (/service/node_modules/mediasoup/lib/Channel.js:199:37)
    at Socket.Channel._consumerSocket.on (/service/node_modules/mediasoup/lib/Channel.js:61:34)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Comment by azhar1038** [comment]
Sorry! My mistake. I forgot to forward the rtc min and max port for docker.

**Comment by azhar1038** [comment]
Also it works only when I set listenIps to something like:
```js
      listenIps: [
        {
          ip: '0.0.0.0',
          announcedIp: '192.168.43.225',
        }
      ],
```
Can you please give some insight about Ip and announcedIp?  
I thought announcedIp is where others will receice stream.

```
Use ip: '0.0.0.0' and announcedIp: HOST_PUBLIC_IP when creating a transport.
```  
I found this in [FAQ of mediasoup](https://mediasoup.org/faq/#running-mediasoup-in-hosts-with-private-ip)

**Comment by mkhahani** [comment]
`ip` is the network address that server starts listening on it and `announcedIp` is the IP address that client connects to. When the server has a public IP and the client is direct to it, then setting the `announcedIp` is unnecessary, although setting both `ip` and `announcedIp` with the same public IP works too.

When the server has several IPs then `0.0.0.0` matches all addresses in the IPv4 address space.

**Comment by mdazharuddin1011999** [comment]
Hello, again I am facing the same issue. This time I am trying to run it on IBM LinuxOne Instance. My public and private IP are same:  148.100.79.193 (as far as I can see). I tried all possible combinations of Ip and announcedIp but it is not working. I have made the required ports accessible to public too.  
![Screenshot (101)](https://user-images.githubusercontent.com/42082172/99495778-260c2f80-2999-11eb-9454-b72f332df488.png)
  
I am using port 2000-2020 as RTC min and max port  
![Screenshot (102)](https://user-images.githubusercontent.com/42082172/99495872-4d62fc80-2999-11eb-9241-f92a2bcc3008.png)
  
I have tried all these combinations of ```ip``` and ```announcedIp```
| ip | announcedIp |
| -- | -------------- |
| 0.0.0.0 | 148.100.79.193 |
| 148.100.79.193 | 148.100.79.193 |
| 148.100.79.193 | null |
