### ISSUE TITLE
Unable to receive remote video

### ISSUE THREAD

**Issue by azhar1038** [mkhahani/mediasoup-sample-app#24]
Hello, I was able to successfully run this sample app locally but when I am trying to run it in IBM LinuxOne instance, I am not receiving the remote video.  
  
**Sender**
![sender](https://user-images.githubusercontent.com/42082172/100053798-c7d2c700-2e46-11eb-8e67-f4f3f239868c.png)
  
**Receiver - Remote video is only loading**
![receiver](https://user-images.githubusercontent.com/42082172/100053878-f486de80-2e46-11eb-8611-992e8bb4eb1e.png)
  
I set the ip and announcedIp as `148.100.79.193` which is the public IP of the instance and there is no other private IP. I even made the required ports publicly accessible and even tried by stopping firewalld.  
![ip](https://user-images.githubusercontent.com/42082172/100054406-f7ce9a00-2e47-11eb-8a5b-f18e14a6e46c.png)

  
I even verified that udp ports are accessible using `nc`  
![udp verify](https://user-images.githubusercontent.com/42082172/100054670-83482b00-2e48-11eb-810e-20606a716dde.png)
    
All I can see in the server logs (with `DEBUG="mediasop*"`) is `RTC::WebRtcTransport::OnRtpDataReceived() | DecryptSrtp() failed` and this happens as soon as I connect the sender.  
![problem](https://user-images.githubusercontent.com/42082172/100054150-85f65080-2e47-11eb-831a-f494e5cbfbcd.png)
  
Can you help me figure out the problem, please?

**Comment by mkhahani** [comment]
Make sure you are opening exactly the same port range in your firewall as in the config file. The default port range is `10000:10100`.

**Comment by azhar1038** [comment]
Yes. I have changed min and max rtc port to 2000-2020 and those are opened for both tcp and udp.

**Comment by mkhahani** [comment]
No idea honestly! Better to ask in mediasoup forum.

**Comment by azhar1038** [comment]
Already asked but no response. Anyway thanks for your time!

If I solve it, I will update here.

**Comment by olzii** [comment]
> Already asked but no response. Anyway thanks for your time!
> 
> If I solve it, I will update here.

Did you solve it ? I also have same problem

**Comment by azhar1038** [comment]
Unfortunately no. I tried but failed :(

Maybe the problem is with LinuxOne and not Mediasoup.
