### ISSUE TITLE
trying to install and test

### ISSUE THREAD

**Issue by samames** [mkhahani/mediasoup-sample-app#25]
I've followed the simple instructions and npm start returns
`> mediasoup-sample-app@1.2.2 start
> browserify client.js -o app-bundle.js; node server.js

sh: 1: browserify: not found
SSL files are not found. check your config.js file
`
I'm trying to set this up on Ubuntu 20.10.
I've checked that I have the snake oil key and pem files and that my config is pointing to them. I'm a little lost now.

**Comment by mkhahani** [comment]
Try `npm i -g browserify`. Regarding SSL files, you need to use absolute path.

**Comment by samames** [comment]
Okay, browserify is installed globally.
The SSL files are being accessed by:
`  sslCrt: '/etc/ssl/certs/ssl-cert-snakeoil.pem',
  sslKey: '/etc/ssl/private/ssl-cert-snakeoil.key',`
and I've verified that those files do exist. Yet, it is still printing `SSL files are not found. check your config.js file`

Would it be related to the security of the private folder? Please tell me how to fix this.

**Comment by mkhahani** [comment]
> Would it be related to the security of the private folder?

Maybe, try `chmod 644 /etc/ssl/certs/*`.

**Comment by samames** [comment]
that worked with sudo. but I have the same error, still! :/

**Comment by samames** [comment]
FYI I'm trying to run this on Ubuntu 20.10

**Comment by samames** [comment]
It's just the .key file that isn't being found, it IS there. I used chmod 644 on that, as well, to no avail...?

**Comment by mkhahani** [comment]
Have you tried `sudo` for running the app?

**Comment by samames** [comment]
yes - the first thing I tried - the same issue.

**Comment by samames** [comment]
I don't think it's a good idea to be running a node app with root privileges, anyway. But I did try it, to no avail.

**Comment by mkhahani** [comment]
No idea honestly.

**Comment by rawnsley** [comment]
If you make the certs relative instead you can add some temporary local versions in config.js:

```
sslCrt: 'certs/ssl-cert-snakeoil.pem',
sslKey: 'certs/ssl-cert-snakeoil.key',
```
Paraphrasing from [this answer](https://stackoverflow.com/a/66604834/671393) you should be able to just do this:

```
openssl genrsa > ssl-cert-snakeoil.key
openssl req -new -x509 -key ssl-cert-snakeoil.key > ssl-cert-snakeoil.pem
```

Regarding browserify: installing it globally didn't work for me (probably MacOS paths), but you can installed it as a devDependency:
```
  "devDependencies": {
    "requirejs": "^2.3.6",
    "browserify": "latest"
  }
```
