### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by habilpekdemir** [mkhahani/mediasoup-sample-app#27]
hi mr mkhahani thanks for sharing this mediasoup-sample i'm at begginer level of mediasoup i tested you sample it works great for video but i can not send and receive audio. Does it support voice ? if yes how we enable it . Thanks

**Comment by mkhahani** [comment]
Hi,

No, the implementation works with a single track for simplicity. Adding support for multi-track stream (audio + video) needs extra work.
