### ISSUE TITLE
can't start the app

### ISSUE THREAD

**Issue by kerolloz** [mkhahani/mediasoup-sample-app#3]
I have just cloned the repo, installed the dependencies, and tried to start the app but it doesn't work.
I'm using Ubutnu 19.04.
![image](https://user-images.githubusercontent.com/36763164/60008376-45077480-9674-11e9-846a-39e6559ef835.png)

**Comment by mkhahani** [comment]
You need to set `sslCrt` and `sslKey` in the **config.js** file.

**Comment by j1elo** [comment]
Just hit this same problem and I think that's a good opportunity right there to improve the instructions given in the README, because technically they don't work as-is

**Comment by j1elo** [comment]
Just for the sake of completeness, for a quick test run I just ended copying and using the default fake cert:

```
/etc/ssl/certs/ssl-cert-snakeoil.pem
/etc/ssl/private/ssl-cert-snakeoil.key
```

that can be found in Debian/Ubuntu systems when the package `ssl-cert` is installed (which normally is, [in most installations](https://askubuntu.com/questions/49196/how-do-i-create-a-self-signed-ssl-certificate/49197#49197))

**Comment by mkhahani** [comment]
Hi @j1elo 
Thanks for the feedback.
I updated the README and set the ssl files in the config.example.js to the predefined OS certificates.
