### ISSUE TITLE
Not an issue, a question

### ISSUE THREAD

**Issue by neilyoung** [mkhahani/mediasoup-sample-app#30]
Hi,

I'm trying to add webrtc data channel support to your app. Unfortunately it is not that easy to get information about this for a beginner and most sample code is completely use case focused bloated. I'm unable to figure out to open a datachannel from the producer and conusme it on the consumer.

Would you mind to provide a small hint? 

TIA

**Comment by mkhahani** [comment]
Although I haven't implemented Data Channels yet, the mediasoup API for Data Channels is just like the Streams API. So it should be easy to implement.

**Comment by neilyoung** [comment]
Not sure what you mean by that, but thanks
