### ISSUE TITLE
Where is app-bundle.js

### ISSUE THREAD

**Issue by vxp123** [mkhahani/mediasoup-sample-app#31]
i see in index.html <script type="text/javascript" src="app-bundle.js"></script>. But it is not in the project folder. Where can I get it or how can I generate it? The readme doesn't say anything about it...

**Comment by mkhahani** [comment]
It's created by the [`npm start` command](https://github.com/mkhahani/mediasoup-sample-app/blob/master/package.json#L7) that's been documented in the README.
