### ISSUE TITLE
Click start webcam, publishing gets failed

### ISSUE THREAD

**Issue by madabhaviamit** [mkhahani/mediasoup-sample-app#5]
Hi @mkhahani,

Application is accessed from chrome browser and clicking on start webcam button with simulcast enabled shows publishing initially, few seconds later publishing gets failed.

Please help..

Thanks, 
Amit M

**Comment by mkhahani** [comment]
Hi
Probably firewall issue. Check your console log for both the client and server.

**Comment by madabhaviamit** [comment]
> Hi
> Probably firewall issue. Check your console log for both the client and server.

Hi @mkhahani, 

I have setup the application on my google cloud VM instance, Firewall is disabled and all the ingress and egress ports are open. Service is up and running now.

Use the link to access the same, **https://34.93.234.144:3000**.
Also, there are no error logs on the server side, and i would want to understand how callback() function is working here.

Request you to access the link once and let me know if further details are required.

**Comment by mkhahani** [comment]
You need to provide a domain. HTTPS connection can not be validated over IP. Check the error log in your browser console.

**Comment by madabhaviamit** [comment]
Hi,

I have a public ip assigned, i am able to connect with https. I request you
to access the link provided once

**Comment by mkhahani** [comment]
Unfortunately the link is not opened for me (the IP seems to be blocked).
You should be able to see the error log via the Chrome console using F12 key.

**Comment by madabhaviamit** [comment]
> Unfortunately the link is not opened for me (the IP seems to be blocked).
> You should be able to see the error log via the Chrome console using F12 key.

Hi @mkhahani ,

The service was shutdown yesterday, It is up and running now. I am not able to see any errors on the console. Can u please try to access it now.

**Comment by mkhahani** [comment]
Some thing must be wrong with your configuration. Have you set the [announcedIp](https://github.com/mkhahani/mediasoup-sample-app/blob/c56853dd354e91b24a2edcffa0340144b9e72cac/config.example.js#L50) in the configuration file? Read more [here](https://mediasoup.org/documentation/v3/mediasoup/api/#TransportListenIp).

Chrome webrtc-internals shows that it's trying to establish connection to IP **10.160.0.2** which is different than **34.93.234.144**:

![image](https://user-images.githubusercontent.com/859377/61031913-b1ed6f00-a3d5-11e9-9cb5-030ea0038c20.png)

Also make sure you've opened the [UDP port range](https://github.com/mkhahani/mediasoup-sample-app/blob/c56853dd354e91b24a2edcffa0340144b9e72cac/config.example.js#L9-L10) in your server firewall.

**Comment by madabhaviamit** [comment]
Hi @mkhahani,

My server's private IP is **10.160.0.2** and the public IP is **34.93.234.144**.

What shall i set in the following configuration for listenIPs?

webRtcTransport: {
      listenIps: [
        {ip: '192.168.1.100', announcedIp: null}
      ],
      maxIncomingBitrate: 1500000,
      initialAvailableOutgoingBitrate: 1000000,
    }

**Comment by madabhaviamit** [comment]
Hi @mkhahani,

I have set IP as private IP and announced IP as Server's Public IP. Now It is working.

Thank you so much for your help. 

We here, are trying to build a Live Streaming App with recording on server with the help of mediasoup. We are still looking at how things work in mediasoup.

**Comment by mkhahani** [comment]
Very good.

>We here, are trying to build a Live Streaming App with recording on server with the help of mediasoup. We are still looking at how things work in mediasoup.

Good luck then.
