### ISSUE TITLE
Click start webcam, not work

### ISSUE THREAD

**Issue by Yang03** [mkhahani/mediasoup-sample-app#6]
Hi @mkhahani,
click webCam, the camera was open, but the local video noting show, the web console has no error; debug i found 
```
 transport.on('connectionstatechange', state => {
})
```
when `state ===connected`  console stream is `undefined`

**Comment by mkhahani** [comment]
Hi
Put a `console.error()` in the catch block to see possible errors:
https://github.com/mkhahani/mediasoup-sample-app/blob/391ada10f4eb4133f8b58d98aec2301910c18d94/client.js#L147-L151

**Comment by Yang03** [comment]
thanks your response
i have try add `console.error` 

![image](https://user-images.githubusercontent.com/10190366/62857307-d8caf800-bd29-11e9-89cf-be529b5805d8.png)

the console
![image](https://user-images.githubusercontent.com/10190366/62857329-ea140480-bd29-11e9-842d-dd03b6abab81.png)

**Comment by mkhahani** [comment]
There must be an error on the server side. Run the following command before running the app to activate the log:
```
export DEBUG="mediasoup*"
npm start
```

**Comment by Yang03** [comment]
thanks
by debug, `state === connected ` run before `getUserMedia` return stream
declare `stream` on top scope,  is ok!
i don't know why ?

**Comment by mkhahani** [comment]
> by debug, state === connected run before getUserMedia

That's impossible. The state will change to `connected` just after a successful `produce()` that is called inside `getUserMedia()`.

Could you check the server log against possible errors?

**Comment by applegrew** [comment]
> > by debug, state === connected run before getUserMedia
> 
> That's impossible. The state will change to `connected` just after a successful `produce()` that is called inside `getUserMedia()`.
> 
> Could you check the server log against possible errors?

What you say is correct and that is the source of error. `getUserMedia` defines a local `stream` variable which it initialises. There before returning that `stream` it invokes https://github.com/mkhahani/mediasoup-sample-app/blob/391ada10f4eb4133f8b58d98aec2301910c18d94/client.js#L181

which causes the code in https://github.com/mkhahani/mediasoup-sample-app/blob/391ada10f4eb4133f8b58d98aec2301910c18d94/client.js#L129 to be executed. The `stream` variable in that closure is still undefined. After that code block is done, the control is back to `producer = await transport.produce(params);` and then getUserMedia` returns the `stream`.

To fix this I moved the codes https://github.com/mkhahani/mediasoup-sample-app/blob/master/client.js#L169...L181

    const track = stream.getVideoTracks()[0];
    const params = { track };
    if ($chkSimulcast.checked) {
      params.encodings = [
        { maxBitrate: 100000 },
        { maxBitrate: 300000 },
        { maxBitrate: 900000 },
      ];
      params.codecOptions = {
        videoGoogleStartBitrate : 1000
      };
    }
    producer = await transport.produce(params);

below https://github.com/mkhahani/mediasoup-sample-app/blob/391ada10f4eb4133f8b58d98aec2301910c18d94/client.js#L148

**Comment by mkhahani** [comment]
@applegrew Thanks for your feedback. It's working for me. Is there possibility for race condition?
